---
- name: install php5 modules
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php5
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-mcrypt
    - php5-json
    - php5-gd
